config/routes.rb
HoursOfHappiness::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  #get "login" => "sessions#new", :as => "login"
  root to: 'pages#home'

  match '/home', { :via => :get, :to => 'pages#home' }
  resources :places
  resources :happy_hours
  resources :ratings
  resources :password_resets
  resources :reports, only: [:new, :create]
end

app/models/happy_hour.rb
class HappyHour < ActiveRecord::Base
  belongs_to :place
  validates :start_time, :end_time, presence: true
end

app/models/place.rb
class Place < ActiveRecord::Base
  validates :name, :description, presence: true

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  has_many :happy_hours
  has_many :ratings
  has_many :reports
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :place
  validates_presence_of :score
  validates_numericality_of :score
  validates_presence_of :review
  validates_presence_of :place_id
end

app/models/report.rb
class Report < ActiveRecord::Base
  validates :place_id, :description, presence: true
  belongs_to :place
  belongs_to :user
  after_create :send_report_email

  def send_report_email
    ReportMailer.admin_report(self).deliver
    ReportMailer.user_report(self).deliver
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  validates :name, :password, presence: true
  validates :email, presence: true, uniqueness: true
  validates :username, uniqueness: true, presence: true
  has_many :reports

  Roles = [ :admin, :default ]

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
    if user
      return user
    else
      registered_user = User.where(:email => access_token.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(name: data["name"],
          provider:access_token.provider,
          email: data["email"],
          photo_url: data["image"].sub('https:', ''),
          uid: access_token.uid ,
          password: Devise.friendly_token[0,20],
          username: data["email"].slice(0...(data["email"].index('@'))),
        )
        user.update(username: (user.username + user.id.to_s))
        return user
      end
    end
  end

  def full_size_pic
    self.photo_url.sub('?sz=50', '')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  CLIENT_SCOPE = 'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/drive.readonly'

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :username) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :username) }
  end
end

app/controllers/happy_hours_controller.rb
class HappyHoursController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @happy_hours = HappyHour.all
  end

  def new
    @happy_hour = HappyHour.new
    @place = Place.find(params[:id])
  end

  def create
    @happy_hour = HappyHour.new(happy_hour_params)
    if @happy_hour.save
      flash[:notice] = "Thanks for adding #{@happy_hour.place.name}!"
      redirect_to @happy_hour.place
    else
      render new_happy_hour_path
    end
  end

  def show
    @happy_hour = HappyHour.find(params[:id])
  end

  def edit
    @happy_hour = HappyHour.find(params[:id])
  end

  def update
    @happy_hour = HappyHour.find(params[:id])
    if @happy_hour.update(happy_hour_params)
      flash[:notice] = "Thanks for the update to #{@happy_hour.place.name}!"
      redirect_to @happy_hour.place
    else
      flash[:notice] = 'Failed to Update'
      render edit_happy_hour_path(@happy_hour)
    end
  end

  def destroy
    @happy_hour = HappyHour.find(params[:id])
    @happy_hour.destroy
    flash[:notice] = "Happy Hour Deleted"
    redirect_to places_path
  end

private
  def happy_hour_params
    params.require(:happy_hour).permit(:place_id, :start_time, :end_time, :details)
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @places = Place.all
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    redirect_to :root
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @places = Place.all
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      flash[:notice] = "Thanks for adding #{@place.name}!"
      redirect_to @place
    else
      render new_place_path
    end
  end

  def show
    @place = Place.find(params[:id])
    @name = @place.name
    @address = @place.address
  end

  def edit
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])
    if @place.update(place_params)
      flash[:notice] = "Thanks for the update to #{@place.name}!"
      redirect_to place_path(@place)
    else
      flash[:notice] = 'Failed to Update'
      render edit_place_path(@place)
    end
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    flash[:notice] = "Account Deleted"
    redirect_to places_path
  end

private
  def place_params
    params.require(:place).permit(:name, :address, :description, :hh_description)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @ratings = Rating.all
  end

  def new
    @rating = Rating.new
    @place = Place.find(params[:id])
    @user = current_user
  end

  def create
    @rating = Rating.new(rating_params)
    if @rating.save
      flash[:notice] = "Thanks for adding #{@rating.place.name}!"
      redirect_to @rating.place
    else
      render new_rating_path
    end
  end

  def show
    @rating = Rating.find(params[:id])
  end

  def edit
    @rating = Rating.find(params[:id])
    @place = @rating.place
  end

  def update
    @rating = Rating.find(params[:id])
    if @rating.update(rating_params)
      flash[:notice] = "Thanks for the update to #{@rating.place.name}!"
      redirect_to @rating.place
    else
      flash[:notice] = 'Failed to Update'
      render edit_rating_path(@rating)
    end
  end

  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy
    flash[:notice] = "Rating Deleted"
    redirect_to ratings_path
  end

private
  def rating_params
    params.require(:rating).permit(:place_id, :user_id, :review, :score)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def new
    @report = Report.new
    @place = Place.find(params[:id])
    @user = current_user
  end

  def create
    @report = Report.new(report_params)
    if @report.save
      flash[:notice] = "Thanks for adding #{@report.place.name}!"
      redirect_to @report.place
    else
      render new_report_path
    end
  end

private
  def report_params
    params.require(:report).permit(:place_id, :user_id, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/happy_hours/_form.html.erb
<%= render 'layouts/errors', object: @happy_hour %>

<%= form_for @happy_hour, :html => { :multipart => true } do |f| %>
  <div class='form-group'>
    <%= f.label :start_time %><br>
    <%= f.time_field :start_time  %>
  </div>
  <div class="form-group">
    <%= f.label :end_time %><br>
    <%= f.time_field :end_time %>
  </div>
  <div class="form-group">
    <%= f.text_area :details, :placeholder => 'Food or Drink specials, gimmicks, music, etc.', rows: 8, cols: 50 %>
  </div>
  <%= f.hidden_field :place_id, value: @place.id %>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/happy_hours/edit.html.erb
<h1>Edit Happy Hour for <%= @happy_hour.place.name %></h1>

<%= render 'form' %>

<%= link_to "Delete Happy Hour", @place, method: "delete", confirm: "Are you sure?" %>

app/views/happy_hours/index.html.erb
<h1>Happy Hours</h1>

<% @happy_hours.each do |happy_hour| %>
  <p>
    Name: <%= happy_hour.place.name %><br>
    Address: <%= happy_hour.place.address %><br>
    Description: <%= happy_hour.place.description %><br>
    <br>
    Happy Hour: <%= happy_hour.start_time.strftime(" %l:M %p") %>
    - <%= happy_hour.end_time.strftime(" %l:M %p") %><br>
    Details: <%= happy_hour.details %><br>
  </p>
<% end %>

app/views/happy_hours/new.html.erb
<h1>Add a new Happy Hour</h1>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="error_messages">
    <h2>Dang! You made some boo-boos:</h2>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HoursOfHappiness</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <%= link_to "Hours of Happiness", root_url,
          :class => "navbar-text navbar-left" %>
      <%= link_to "Add New Place", new_place_path,
          :class => "navbar-text navbar-left" %>
      <% if user_signed_in? %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete,
            :class => "navbar-text navbar-right" %>
        <%= image_tag current_user.photo_url, :class => "nav-photo navbar-right" %>
        <%= link_to "Logged in as #{current_user.name}", edit_user_registration_path,
            :class => "navbar-text navbar-right" %>
      <% else %>
        <%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2), :class => "navbar-text navbar-right" %>
        <%= link_to "Sign in", new_user_session_path,
            :class => "navbar-text navbar-right" %>
        <%= link_to "Sign up", new_user_registration_path,
            :class => "navbar-text navbar-right" %>
      <% end %>
    </div>
  </div>

  <div class="container">
    <%= flash[:notice] %>
    <%= flash[:alert] %>
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/home.html.erb
<h2>We're here to help you find Hours of Happiness</h2>

<div class="row">
  <div class="col-sm-8">
    <ul>
      <% @places.each do |place| %>
        <li id="home"><%= link_to "#{place.name}", place_path(place) %>
      <% end %>
    </ul>
  </div>
  <div class="col-sm-4">
    <%= image_tag current_user.full_size_pic if current_user %>
  </div>
</div>

app/views/password_resets/new.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="actions"><%= submit_tag "Reset Password" %></div>
<% end %>

app/views/places/_form.html.erb
<%= render 'layouts/errors', object: @place %>

<%= form_for @place, :html => { :multipart => true } do |f| %>
  <div class='form-group'>
    <%= f.text_field :name, :placeholder => 'Name'  %>
  </div>
  <div class="form-group">
    <%= f.text_field :address, :placeholder => 'Address' %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, :placeholder => 'Description', rows: 8, cols: 50 %>
  </div>
  <div class="form-group">
    <%= f.text_area :hh_description, :placeholder => 'Happy Hour Description', rows: 4, cols: 50 %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/places/edit.html.erb
<h1>Edit <%= @place.name %></h1>

<%= render 'form' %>

<%= link_to "Delete Place", @place, method: "delete", confirm: "Are you sure?" %>

app/views/places/index.html.erb
<h1>Places</h1>

<% @places.each do |place| %>
  <p>
    Name: <%= place.name %><br>
    Address: <%= place.address %><br>
    Description: <%= place.description %><br>
    Happy Hour Description: <%= place.hh_description %><br>
  </p>
<% end %>

app/views/places/new.html.erb
<h1>Add a new place</h1>

<%= render 'form' %>

app/views/places/show.html.erb
<h1><%= @place.name %>   <%= link_to "Edit Place", edit_place_path(@place), class: "btn btn-primary btn-sm" %></h1>   <h6><%= link_to "Report Content", new_report_path(id: @place.id) %></h6><br>

<div class="row">
  <div class="col-sm-6">
    <% if @place.address %>
      <h4>Address: <br></h4>
        <%= @place.address %><br>
    <% end %>

    <h4>Description: <br></h4>
      <%= @place.description %><br><br>

    <% if @place.happy_hours.length > 0 %>
      <h2>Happy Hour</h2>
      <h4>Details:<br></h4>
        <%= @place.happy_hours.first.details %><br>

      <h4>
        Time:
        <%= @place.happy_hours.first.start_time.strftime(" %l:%M %p ") %> -
        <%= @place.happy_hours.first.end_time.strftime(" %l:%M %p ") %><br><br>
      </h4>
    <% else %>
      <h4>
        Does <%= @place.name %> have happy hour?<br></h4>
        <%= link_to "Add Happy Hour", new_happy_hour_path(id: @place.id), :class => "btn btn-primary" %>
    <% end %>

    <h4>Reviews</h4>
    <% if @place.ratings.count > 0 %>
      <% @place.ratings.order(:updated_at).each do |rating| %>
        <h2>
          <% rating.score.times do %>
            <img src="http://openclipart.org/image/45px/svg_to_png/73591/beer1.png">
          <% end %>
        </h2>
        <p><%= rating.review %></p>
        <% if current_user && rating.user_id == current_user.id %>
          <%= link_to "Edit Review", edit_rating_path(rating), class: "btn btn-warning btn-sm" %>
        <% elsif %>
          <h4>You have not reviewed <%= @place.name %></h4>
          <%= link_to "Add Rating", new_rating_path(id: @place.id), class: "btn btn-primary" %>
        <% end %>
      <% end %>
    <% else %>
      <h4><%= @place.name %> hasn't been reviewed yet. Be the first!</h4>
      <%= link_to "Add Rating", new_rating_path(id: @place.id), class: "btn btn-primary" %>
    <% end %>
  </div>
  <div class="col-sm-6">
    <% if @address %>
      <iframe
        width="600"
        height="450"
        frameborder="0" style="border:0"
        src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAzW0SvELhV_eiTPvfxBtHrGd5oBozh2Uc
          &q=<%= @name %>+<%= @address %>">
    <% else %>
      <iframe
        width="600"
        height="450"
        frameborder="0" style="border:0"
        src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAzW0SvELhV_eiTPvfxBtHrGd5oBozh2Uc
          &q=<%= @name %>">
    <% end %>
      </iframe>
  </div>

</div>

app/views/ratings/_form.html.erb
<%= render 'layouts/errors', object: @rating %>

<%= form_for @rating, :html => { :multipart => true } do |f| %>
  <div class='form-group'>
    <h4>Rating</h4>
    <h2>
      <%= f.radio_button :score, "5" %>
      <%= f.label "\u2605 \u2605 \u2605 \u2605 \u2605" %><br>
      <%= f.radio_button :score, "4" %>
      <%= f.label "\u2605 \u2605 \u2605 \u2605" %><br>
      <%= f.radio_button :score, "3" %>
      <%= f.label "\u2605 \u2605 \u2605" %><br>
      <%= f.radio_button :score, "2" %>
      <%= f.label "\u2605 \u2605" %><br>
      <%= f.radio_button :score, "1" %>
      <%= f.label "\u2605" %><br>
    </h2>
  </div>
  <div class="form-group">
    <%= f.text_area :review, :placeholder => 'What did you like/dislike?', rows: 8, cols: 50 %>
  </div>
  <%= f.hidden_field :place_id, value: @place.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/ratings/edit.html.erb
<h1>Edit review for <%= @rating.place.name %></h1>

<%= render 'form' %>

<%= link_to "Delete Review", @rating, method: "delete", confirm: "Are you sure?", class: "btn btn-danger" %>

app/views/ratings/new.html.erb
<h1>Add a new review</h1>

<%= render 'form' %>

app/views/reports/_form.html.erb
<%= render 'layouts/errors', object: @report %>

<%= form_for @report, :html => { :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.text_area :description, :placeholder => 'Were there typos? or F-bombs? or racism/sexism/other-ism?', rows: 8, cols: 50 %>
  </div>
  <%= f.hidden_field :place_id, value: @place.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/reports/new.html.erb
<h1>Tell us what was erroneous or offensive:</h1>

<%= render 'form' %>